### ISSUE TITLE
Caesar Decryption error

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Plasmosis#7]
The Caesar Decryption doesn't work properly with large value in key

**Comment by cwade12c** [comment]
Encrypted string: "aaa"
Shift: 1
Iteration: 1

char c = 'a'
int j = 0;

j = (j - shift) mod 26
j = -1

But -1 mod 26 = 25.

**Comment by shawnkoon** [comment]
oh what the heck??

**Comment by shawnkoon** [comment]
great job

added few changes together

if (j - shift < 0)
                    j = len + ((j - shift) % len);
                else
                    j = (j - shift) % len;

                if (j == len)
                {
                    j = j % len;
                }
